version: '3'

services:
  demo-api-pg:
    build: .
    image: golang:1.14
    volumes:
      - .:/go/src/
      - ./.netrc:/root/.netrc
    working_dir: /go/src/
    ports:
      - "6552:6552"
    depends_on:
      - redis
      - postgres
    environment:
      - GOPROXY=https://goproxy.cn
      - GOPRIVATE=github.com/secure-for-ai
      - ENV=prod
    container_name: secureai-dev-demo-api-pg
    entrypoint: go run main.go
  postgres:
    image: postgres:12
    ports:
      - "7000:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./pg-init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=test
      - POSTGRES_DB=test
    container_name: secureai-dev-postgres
  redis:
    image: redis
    ports:
      - "6379:6379"
    environment:
      - RedisPass=password
    volumes:
      - ./data/redis:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    container_name: secureai-dev-redis
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - demo-api-pg:demo-api-pg
    container_name: secureai-dev-nginx
